# Generated by Django 4.0.6 on 2022-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=150)),
                ('Author', models.CharField(default='', max_length=80)),
                ('Downloads', models.IntegerField(default=0)),
                ('Pages', models.IntegerField(default=0)),
                ('Size', models.FloatField(default=0)),
                ('Description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='media/images')),
                ('pdf', models.FileField(default='', upload_to='media/pdf')),
            ],
        ),
    ]
