# Generated by Django 4.0.6 on 2022-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softLib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='', upload_to='pdf'),
        ),
    ]
