# Generated by Django 4.0.6 on 2022-11-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softLib', '0006_rename_added_by_book_addby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Addby',
        ),
    ]
