# Generated by Django 4.0.6 on 2022-11-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softLib', '0008_book_addby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Addby',
        ),
    ]
