# Generated by Django 4.0.6 on 2022-12-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('softLib', '0010_book_addby'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Review',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Comments', models.TextField()),
                ('Like', models.IntegerField(default=0)),
                ('Book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='softLib.book')),
                ('Commentby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
