# Generated by Django 4.0.6 on 2023-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softLib', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
